FROM php:8.1.3-fpm as base

WORKDIR /srv/<%= packageName %>

RUN curl --fail --location --output /usr/local/bin/install-php-extensions https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/1.0.4/install-php-extensions && \
    echo "8bb61096c6cb1edc4d5039cf085c0e774f222c45d3f0546f3c58053a58253fb7 /usr/local/bin/install-php-extensions" | sha256sum -c - && \
    chmod 755 /usr/local/bin/install-php-extensions

RUN install-php-extensions intl pdo_pgsql

# Dependencies
FROM base as dependencies

RUN apt-get update && \
    apt-get install --yes --no-install-recommends git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN curl -f -L "https://getcomposer.org/download/2.2.6/composer.phar" -o /usr/local/bin/composer && \
    echo "1d58486b891e59e9e064c0d54bb38538f74d6014f75481542c69ad84d4e97704 /usr/local/bin/composer" | sha256sum -c - && \
    chmod 755 /usr/local/bin/composer

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-scripts

<% if (twig) { %>
# Webpack
FROM node:16.15.0 as webpack

WORKDIR /srv/<%= packageName %>

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY ./.babelrc ./.browserslistrc ./postcss.config.js ./webpack.config.js ./
COPY ./assets/ ./assets/

ENV NODE_ENV=production
RUN yarn build

# Sentry release
FROM getsentry/sentry-cli:1.61.0 as sentry

WORKDIR /srv/<%= packageName %>/

COPY --from=webpack /srv/<%= packageName %>/assets /srv/<%= packageName %>/assets
<% } %>

# PHP
FROM base as php

COPY --from=dependencies /srv/<%= packageName %>/vendor /srv/<%= packageName %>/vendor
COPY ./bin ./bin
COPY ./config ./config
COPY ./migrations ./migrations
COPY ./public ./public
COPY ./src ./src
<% if (twig) { %>
COPY ./templates ./templates
<% } %>
COPY ./translations ./translations

ENV APP_ENV=prod

RUN ./bin/console cache:warmup

<% if (twig) { %>
COPY --from=webpack /srv/<%= packageName %>/var/manifest.json /srv/<%= packageName %>/var/manifest.json
<% } %>

# NginX
FROM nginx:1.21.6 as nginx

COPY ./default.conf /etc/nginx/conf.d/

<% if (twig) { %>
COPY --from=webpack /srv/<%= packageName %>/public/assets/ /srv/<%= packageName %>/public/assets/
<% } %>
