FROM php:8.0.7-fpm

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install extensions
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/572050a69b646d596b93b421abdff4426a4a679b/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions
RUN install-php-extensions intl pdo_pgsql

# Install composer
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --yes --no-install-recommends git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN curl -f -L "https://getcomposer.org/download/2.0.8/composer.phar" -o /usr/local/bin/composer && \
    echo "2021f0d52b446e0efe3c548cc058ab5671fa38cdbcf814e7911c7e9d71d61538 /usr/local/bin/composer" | sha256sum -c - && \
    chmod 755 /usr/local/bin/composer

# Configure permissions
ARG UID=1000
RUN useradd --uid $UID --create-home user
USER user

WORKDIR /usr/src/project/<%= packageName %>
