---
- hosts: server
  tasks:
    - name: List packages
      find:
        paths: '{{ playbook_dir }}/packages'
        file_type: directory
      delegate_to: localhost
      register: packages
    - name: Include packages deployment
      include_tasks: '{{ package.path }}/deployment.yaml'
      loop: '{{ packages.files }}'
      loop_control:
        loop_var: package
  vars_files:
    - vars/github.yaml
