# Base image for all steps
FROM node:22.13.0-slim as base

WORKDIR /srv/<%= packageName %>/

# Dev dependencies
FROM base as dev-dependencies

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

# Prod dependencies
FROM dev-dependencies as dependencies

RUN yarn install --frozen-lockfile --production

# Build
FROM dev-dependencies as build

COPY index.html tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts ./
COPY public ./public
COPY src ./src

ARG VERSION
RUN echo "export default '$VERSION';" > src/version.ts

RUN yarn build && yarn create-template && rm dist/index.html
RUN cp --recursive dist dist-final && rm dist-final/assets/*.map

# Sentry release
FROM getsentry/sentry-cli:1.61.0 as sentry

WORKDIR /srv/<%= packageName %>/

COPY --from=build /srv/<%= packageName %>/dist /srv/<%= packageName %>

# Final image
FROM nginx:1.21.0

WORKDIR /srv/<%= packageName %>/

COPY --chmod=755 <<EOF /docker-entrypoint.d/25-envsubst-index.sh
#!/bin/sh
set -e
envsubst < /srv/<%= packageName %>/index.html.template > /srv/<%= packageName %>/index.html
rm /srv/<%= packageName %>/index.html.template
EOF

COPY default.conf /etc/nginx/conf.d

COPY --from=build /srv/<%= packageName %>/dist-final /srv/<%= packageName %>
