# Base image for all steps
FROM node:18.16.0-slim as base

WORKDIR /srv/<%= packageName %>/

# Dev dependencies
FROM base as devDependencies

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

# Prod dependencies
FROM devDependencies as dependencies

RUN yarn install --frozen-lockfile --production

# Build
FROM devDependencies as build

COPY index.html tsconfig.json tsconfig.node.json vite.config.ts vite.config.ts ./
COPY public ./public
COPY src ./src

ARG VERSION
RUN echo "export default '$VERSION';" > src/version.ts

RUN yarn build
RUN cp --recursive dist dist-final && rm dist-final/assets/*.map

# Sentry release
FROM getsentry/sentry-cli:1.61.0 as sentry

WORKDIR /srv/<%= packageName %>/

COPY --from=build /srv/<%= packageName %>/dist /srv/<%= packageName %>

# Final image
FROM nginx:1.21.0

WORKDIR /srv/<%= packageName %>/

COPY default.conf /etc/nginx/conf.d
COPY start.sh /usr/local/bin

COPY --from=build /srv/<%= packageName %>/dist-final /srv/<%= packageName %>

CMD ["start.sh"]
