version: '2.1'

orbs:
  node: circleci/node@4.5.1
  php: circleci/php@1.1.0
  terraform: circleci/terraform@3.0.0

executors:
  node:
    docker:
      - image: circleci/node:14.17.5

jobs:
  yarn-install:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint

  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build

  test-utils:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sudo apt install ansible
      - run: yarn test:utils

workflows:
  version: '2'
  build:
    jobs:
      - yarn-install
      - lint:
          requires:
            - yarn-install
      - build:
          requires:
            - yarn-install
      - test-utils:
          requires:
            - yarn-install
