version: '2.1'

orbs:
  php: circleci/php@1.1.0

executors:
  node:
    docker:
      - image: circleci/node:14.15.1

jobs:
  yarn-install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-install-{{ checksum "package.json" }}
            - yarn-install
          paths:
            - node_modules
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint

  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build

  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sudo apt install ansible apt-transport-https
      - php/install-php:
          version: '8.0'
      - php/install-composer:
          install-version: 2.0.11
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-cache-{{ .Branch }}
            - yarn-cache
      - run: yarn test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.cache/yarn

workflows:
  version: '2'
  build:
    jobs:
      - yarn-install
      - lint:
          requires:
            - yarn-install
      - build:
          requires:
            - lint
      - test:
          requires:
            - lint
