version: '2.4'

services:
    nginx:
        build: ./nginx/docker
        ports:
            - ${PORT:-80}:80

    postgres:
        build: ./postgres/docker
        environment:
            PGUSER: user
            PGPASSWORD: password
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
