version: '2.4'

services:
    postgres:
        build: ./postgres/docker
        environment:
            PGUSER: user
            PGPASSWORD: password
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
