#!/bin/sh
# Resolve all dependencies that the application requires to run.

set -e

cd $(dirname $(dirname $0))

. script/lib/docker

docker-compose run --rm --no-deps test yarn install --frozen-lockfile
