FROM node:14.17.6

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN curl --fail --location --output /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/81b1373f17855a4dc21156cfe1694c31d7d1792e/wait-for-it.sh && \
    echo "b7a04f38de1e51e7455ecf63151c8c7e405bd2d45a2d4e16f6419db737a125d6 /usr/local/bin/wait-for-it" | sha256sum -c - && \
    chmod 755 /usr/local/bin/wait-for-it

RUN userdel node

ARG UID
RUN useradd --non-unique --uid $UID --create-home user
USER user

WORKDIR /usr/src/project/<%= packagePath %>

ENV PATH="/usr/src/project/<%= packagePath %>/node_modules/.bin:${PATH}"

CMD ["wait-for-it", "postgres:5432", "--", "yarn", "start"]
