FROM node:<%= nodeVersion %>

RUN userdel node

ARG UID=1000
RUN useradd --uid $UID --create-home user
USER user

WORKDIR /usr/src/project/<%= name %>

ENV PATH="/usr/src/project/<%= name %>/node_modules/.bin:${PATH}"

CMD ["yarn", "start"]
