# Base image for all steps
FROM node:18.16.0-slim as base

WORKDIR /srv/<%= packageName %>/

# Dev dependencies
FROM base as dev-dependencies

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

# Prod dependencies
FROM dev-dependencies as dependencies

RUN yarn install --frozen-lockfile --production

# Build
FROM dev-dependencies as build

COPY tsconfig.json next.config.js ./
COPY pages ./pages

ARG VERSION
RUN echo "export default '$VERSION';" > version.ts

RUN yarn build

# Final image
FROM base

COPY next.config.js ./
COPY --from=dependencies /srv/<%= packageName %>/node_modules /srv/<%= packageName %>/node_modules
COPY --from=build /srv/<%= packageName %>/build /srv/<%= packageName %>/build

USER node

ENV NODE_ENV="production"
ENV PATH="/srv/<%= packageName %>/node_modules/.bin:${PATH}"

EXPOSE 3000

CMD ["next", "start"]
