# Base image for all steps
FROM node:20.12.0-slim as base

WORKDIR /srv/<%= packageName %>/

# Dev dependencies
FROM base as dev-dependencies

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

# Prod dependencies
FROM dev-dependencies as dependencies

RUN yarn install --frozen-lockfile --production

# Build
FROM dev-dependencies as build

COPY --from=dev-dependencies /srv/<%= packageName %>/node_modules ./node_modules
COPY . .

ARG VERSION
RUN echo "export default '$VERSION';" > src/version.ts

RUN yarn build

# Final image
FROM base

COPY --from=build /srv/<%= packageName %>/public ./public
COPY --from=build /srv/<%= packageName %>/.next/standalone .
COPY --from=build /srv/<%= packageName %>/.next/static ./.next/static

USER node

ENV NODE_ENV="production"
ENV PATH="/srv/<%= packageName %>/node_modules/.bin:${PATH}"

EXPOSE 3000

CMD ["node", "server.js"]
