version: '2.1'

orbs:
  node: circleci/node@4.5.1

executors:
  node:
    docker:
      - image: circleci/node:14.17.6
  php:
    docker:
      - image: circleci/php:8.0.7

jobs: []

workflows:
  version: '2'
  build:
    jobs: []
