# Base image for all steps
FROM node:16.15.0-slim as base

WORKDIR /srv/<%= packageName %>/

# Dev dependencies
FROM base as devDependencies

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

# Prod dependencies
FROM devDependencies as dependencies

RUN yarn install --frozen-lockfile --production

# Build
FROM devDependencies as build

COPY tsconfig.json .
COPY src ./src

ARG VERSION
RUN echo "export default '$VERSION';" > src/version.ts

RUN yarn build

# Final image
FROM base

COPY ormconfig-dist.js ./ormconfig.js
COPY --from=dependencies /srv/<%= packageName %>/node_modules /srv/<%= packageName %>/node_modules
COPY --from=build /srv/<%= packageName %>/dist /srv/<%= packageName %>/dist

USER node

ENV NODE_ENV="production"
ENV PATH="/srv/<%= packageName %>/node_modules/.bin:${PATH}"

EXPOSE 3000

CMD ["node", "dist"]
