name: CI

on:
  push: ~

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build

  test-utils:
    strategy:
      matrix:
        node-version: [18.20.4, 20.18.0, 22.11.0]
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt update && sudo apt install ansible
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --immutable
      - run: yarn test:utils

  test-generators:
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    runs-on: ubuntu-22.04
    steps:
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 3.8.0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - run: git config --global init.defaultBranch main
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: yarn
      - run: yarn install --immutable
      - run: yarn test:generators --shard=${{ matrix.shard }}

  test-update-scripts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 22.11.0
          cache: yarn
      - run: yarn install --immutable
      - name: Update Node version
        run: ./scripts/updateNode.mjs >> $GITHUB_OUTPUT
      - name: Update PHP version
        run: ./scripts/updatePHP.mjs >> $GITHUB_OUTPUT
