name: CI

on:
  push: ~

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.0
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.0
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

  test-utils:
    strategy:
      matrix:
        node-version: [18.20.0, 20.12.0]
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt update && sudo apt install ansible
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test:utils

  test-generators:
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    runs-on: ubuntu-22.04
    steps:
      - uses: azure/setup-helm@v1
        with:
          version: 3.8.0
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - run: git config --global init.defaultBranch main
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.0
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test:generators --shard=${{ matrix.shard }}

  test-update-script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: Update version
        run: ./scripts/updateNode.ts
